[properties]
title=quickdev16
author=
productcode=
packagecode=
upgradecode=
version=
comments=
supporturl=
eulafile=
language=en
bannerfile=
noquestions=false
[files]
file0path=C:\msys\1.0\home\david\ucon64\src\win32\quickdev16.inf
file1path=C:\msys\1.0\home\david\ucon64\src\win32\quickdev16.cat
file2path=C:\msys\1.0\home\david\ucon64\src\win32\quickdev16_x64.cat
file3path=C:\msys\1.0\home\david\ucon64\src\win32\ucon64.exe
file3shortcutname=Quickdev16
